services:
  web:
    image: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/user/PhpstormProjects/online-shop:/var/www/html
    ports:
      - 80:80

  php-fpm:
    build: ./docker
    volumes:
      - .:/var/www/html

  postgres:
    image: postgres:13.1
#    volumes:
#      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 54324:5432
