services:
  web:
    image: nginx
    ports:
      - 81:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/user/PhpstormProjects/environment:/var/www/html

  php-fpm:
    container_name: php-fpm
    build: ./docker
    volumes:
      - .:/var/www/html

  postgres:
    container_name: postgres_db
    image: postgres:13.1
#    volumes:
#      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 54324:5432
